spring:   
   datasource:
    url: jdbc:mysql://localhost:3306/falm?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root
    initialization-mode: always
   jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:  
      ddl-auto: create-drop
   main:
    allow-bean-definition-overriding: true         
server:  port: 8080