spring:   
   datasource:
    url: jdbc:mysql://localhost:3306/falm?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
   jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    hibernate:  
      ddl-auto: create    
   main:
    allow-bean-definition-overriding: true      
server:  port: 8080